---
apiVersion: v1
kind: Service
metadata:
  name: payment-project
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: payment-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
